In [104]:
import pandas as pd
df = pd.read_excel("data/cardiac_patient_data.xlsx")
df.head()

,Data przyjęcia,cid,Data przyjęcia.1,data implantacji,data zgonu lub konca obserwacji,Unnamed: 5,zgon,LVEF,Wskazania,typo urządzenia,...,"TR_ica,ICA,RI-iCA","TR_ica,ICA,Upośledzenie przepływu > 50%","TR_va,VA,Przepływ dogłowowy","TL_cca,CCA,Vdiff","TL_cca,CCA,PP","TL_cca,CCA,RI","TL_cca,CCA,DS.","TL_cca,CCA,MV","TL_cca,CCA,MP","TL_cca,CCA,FPP"
0,2012-05-22,393,2012-05-22,2012-03-23,2016-04-01 00:00:00,1410.0,1,40.76,zawal_pierwotna,ICD_D,...,0.87,0.0,NaN,49.1,1.325700,0.842196,0.157804,33.75,0.475756,2.786512
1,2011-11-07,350,2011-11-07,2009-11-12,2020-03-16 00:00:00,3052.0,1,38.78,zawal_pierwotna,ICD_D,...,0.67,0.0,1.0,56.4,2.219904,0.728682,0.271318,49.20,0.916368,2.422503
2,2011-11-09,352,2011-11-09,2011-01-17,2016-11-16 00:00:00,1834.0,1,18.82,niewydolnosc_pierwotna,crtd2,...,0.54,0.0,1.0,32.8,0.795072,0.702355,0.297645,30.30,0.342308,2.322680
3,2011-03-09,170,2011-03-09,2009-07-13,2018-06-01 00:00:00,2641.0,1,29.99,zawal_pierwotna,ICD_D,...,0.58,0.0,0.0,36.3,1.038180,0.673469,0.326531,35.75,0.469964,2.209063
4,2010-12-06,61,2010-12-06,2008-09-24,31.04.2020,NaN,0,30.92,zawal_pierwotna,ICD_D,...,0.63,0.0,0.0,47.4,1.444752,0.766990,0.233010,38.10,0.564528,2.559221

In [105]:
# print(df['Data przyjęcia'].equals(df['Data przyjęcia.1']))
df.drop(columns=['Data przyjęcia.1'], inplace=True)     # duplicated column

df['data zgonu lub konca obserwacji'] = df['data zgonu lub konca obserwacji'].astype(str).str.replace('31.04.2020', '2020-04-30 00:00:00')   
df['data zgonu lub konca obserwacji'] = pd.to_datetime(df['data zgonu lub konca obserwacji'], format='%Y-%m-%d %H:%M:%S')
# invalid date, ask for confirmation

df['Unnamed: 5'] = df['data zgonu lub konca obserwacji'] - df['Data przyjęcia']
df.rename(columns={'Unnamed: 5': 'Time of observation'}, inplace=True)
# correction of column corupted by invalid date

In [112]:
df.convert_dtypes()
df.to_csv("data/cardiac_patient_data.csv", index=False)
df.head()

,Data przyjęcia,cid,data implantacji,data zgonu lub konca obserwacji,Time of observation,zgon,LVEF,Wskazania,typo urządzenia,elektroda rv,...,"TR_ica,ICA,RI-iCA","TR_ica,ICA,Upośledzenie przepływu > 50%","TR_va,VA,Przepływ dogłowowy","TL_cca,CCA,Vdiff","TL_cca,CCA,PP","TL_cca,CCA,RI","TL_cca,CCA,DS.","TL_cca,CCA,MV","TL_cca,CCA,MP","TL_cca,CCA,FPP"
0,2012-05-22,393,2012-03-23,2016-04-01,1410 days,1,40.76,zawal_pierwotna,ICD_D,apex,...,0.87,0.0,NaN,49.1,1.325700,0.842196,0.157804,33.75,0.475756,2.786512
1,2011-11-07,350,2009-11-12,2020-03-16,3052 days,1,38.78,zawal_pierwotna,ICD_D,apex,...,0.67,0.0,1.0,56.4,2.219904,0.728682,0.271318,49.20,0.916368,2.422503
2,2011-11-09,352,2011-01-17,2016-11-16,1834 days,1,18.82,niewydolnosc_pierwotna,crtd2,apex,...,0.54,0.0,1.0,32.8,0.795072,0.702355,0.297645,30.30,0.342308,2.322680
3,2011-03-09,170,2009-07-13,2018-06-01,2641 days,1,29.99,zawal_pierwotna,ICD_D,apex,...,0.58,0.0,0.0,36.3,1.038180,0.673469,0.326531,35.75,0.469964,2.209063
4,2010-12-06,61,2008-09-24,2020-04-30,3433 days,0,30.92,zawal_pierwotna,ICD_D,apex,...,0.63,0.0,0.0,47.4,1.444752,0.766990,0.233010,38.10,0.564528,2.559221